#ifndef ERRORS
#define ERRORS

enum class Errors{
    CLIENT_IN_CLUB,
    CLUB_IS_NOT_OPEN,
    PLACE_IS_BUSY,
    CLIENT_UNKNOWN,
    CANT_WAIT,
    IN_QUEUE,
    CLIENT_LEFT,
    CLIENT_FROM_QUEUE,
    CLIENT_IN_QUEUE,
    QUEUE_IS_FULL,
    NO_ERROR
};
#endif